import { Inter } from "next/font/google";
import "./globals.css";
import "./rosters/page.js";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Minimally Entertaining NonChildbearing Sport Advocates</h1>
            <Link href="/" className="nav-link"> Home Page   </Link>

            <Link href="/rosters" className="nav-link">Rosters Page    
            </Link>

            <Link href="/recentTransactions" className="nav-link">Recent Transactions   
            </Link>

            <Link href="/matchups" className="nav-link">Weekly Matchups
            </Link>
            <h2> League History </h2>
            
        </header>

        <hr></hr>
        <main>{children}</main>
        <hr></hr>

        <footer>Created by Samuel Garmoe - 2025</footer>
      </body>
    </html>
  );
}
