import { Inter } from "next/font/google";
import "./globals.css";
import "./rosters/page.js";
import Button from '@mui/material/Button';
import { ButtonGroup } from '@mui/material';
import Stack from '@mui/material/Stack';
import Divider from '@mui/material/Divider';
import { createTheme, ThemeProvider } from '@mui/material/styles';



//TODO
//color scheme for header:
  //MENSA not showing white
  //buttons should be orange, not space between them
//clean up button experimenting
//set actual button layouts for header and footer
//properly plan color, MENSA text appearance, etc. 


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 >Minimally Entertaining NonChildbearing Sport Advocates</h1>
            <Stack 
            direction="row" 
            spacing={5}
            divider={<Divider orientation="vertical" flexItem/> } 
            sx={{
              justifyContent: "center",
              alignItems: "center",
              bgcolor: "orange",
              color: "black",
            }}

            >
              <Button href="/" variant="contained">Home</Button>
              <Button href="/rosters" variant="contained">Rosters</Button>
              <Button href="/recentTransactions" variant="contained">Recent Transactions</Button>
              <Button href="/matchups" variant="contained">Matchups</Button>
              <Button href="/history" variant="contained">League History</Button>
            </Stack>
        </header>

        <hr></hr>
        <main>{children}</main>
        <hr></hr>

        <footer >
            <Stack 
            direction="row" 
            spacing={10}
            divider={<Divider orientation="vertical" flexItem/> } 
            sx={{
              justifyContent: "center",
              alignItems: "center",
            }}
            >
              <Button href="/">Home</Button>
              <Button href="/rosters">Rosters</Button>
              <Button href="/recentTransactions">Recent Transactions</Button>
              <Button href="/matchups">Matchups</Button>
              <Button href="/history">League History</Button>
            </Stack>
          <p className="attribute-self"> Created by Samuel Garmoe: 2024-2026 </p>
        </footer>
      </body>
    </html>
  );
}
